[package]
name = "ultraviolet"
version = "0.6.0-alpha0"
authors = ["Gray Olson <gray@grayolson.com>"]
edition = "2018"
description = "A crate to do linear algebra, fast."
repository = "https://github.com/termhn/ultraviolet"
readme = "README.md"
keywords = ["simd", "wide", "graphics", "math", "linear-algebra"]
license = "MIT OR Apache-2.0 OR Zlib"

[dependencies]
# wide = { path = "../wide", optional = true }
# wide = { version = "~0.5.1", optional = true }
wide = { git = "https://github.com/termhn/wide", branch = "main", optional = true }
serde = { version = "1.0", features = [], optional = true }
# packed_simd = { version = "~0.3.3", optional = true }
# packed_simd = { path = "../packed_simd", optional = true }
packed_simd = { git = "https://github.com/termhn/packed_simd", branch = "sincos_acos", optional = true }

[features]
default = [ "wide" ]
nightly = [ "packed_simd" ]

[dev-dependencies]
serde_test = "1.0"
