[package]
name = "ultraviolet"
version = "0.3.1"
authors = ["Gray Olson <gray@grayolson.com>"]
edition = "2018"
description = "A crate to do linear algebra, fast."
repository = "https://github.com/termhn/ultraviolet"
readme = "README.md"
keywords = ["simd", "wide", "graphics", "math", "linear-algebra"]
license = "MIT OR Apache-2.0"

[dependencies]
# wide = { path = "../wide" }
wide = "0.3"