[package]
name = "widehard"
version = "0.1.0"
authors = ["Gray Olson <gray@grayolson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wide = "0.1"