[package]
name = "ultraviolet"
version = "0.1.0"
authors = ["Gray Olson <gray@grayolson.com>"]
edition = "2018"
description = "A crate to do linear algebra, fast."
repository = "https://github.com/termhn/ultraviolet"
readme = "README.md"
keywords = ["simd", "wide", "termhn", "grpahics", "math", "linear algebra"]
license = "MIT OR Apache-2.0"

[dependencies]
wide = "0.2"